sudo: required
services:
  - docker

# temp no test
# # this portion is only for testing
# before_install: 
#   - docker build -t react-test -f ./client/Dockerfile.dev ./client

# script:
#   - docker run -e CI=true react-test npm run test
# # end testing part here

before_install:
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install

env:
  - PATH=$PATH:/usr/local/aws-cli/v2/current/bin

script: 
  - chmod +x ./aws-ecs.sh
  - ./aws-ecs.sh
  # - echo Building Images...
  # - docker build -t multi-server ./server
  # - docker build -t multi-nginx ./nginx
  # - docker build -t multi-worker ./worker
  # - docker build -t multi-client ./client - ./client/Dockerfile ./client
  # - echo Tagging Images...
  # - docker tag multi-client public.ecr.aws/m4x4f7z6/docker-multi-test:multi-client
  # - docker tag multi-server public.ecr.aws/m4x4f7z6/docker-multi-test:multi-server
  # - docker tag multi-nginx public.ecr.aws/m4x4f7z6/docker-multi-test:multi-nginx
  # - docker tag multi-worker public.ecr.aws/m4x4f7z6/docker-multi-test:multi-worker
  # - echo Pusing Images...
  # - docker push public.ecr.aws/m4x4f7z6/docker-multi-test:multi-client
  # - docker push public.ecr.aws/m4x4f7z6/docker-multi-test:multi-server
  # - docker push public.ecr.aws/m4x4f7z6/docker-multi-test:multi-nginx
  # - docker push public.ecr.aws/m4x4f7z6/docker-multi-test:multi-worker


deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-multi-react"
  env: "Docker-multi-react-env"
  bucket_name: "elasticbeanstalk-eu-central-1-156173772875"
  bucket_path: "docker-multi-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret-acces-key: $AWS_SECRET_KEY
